root = "."
tmp_dir = ".air"

[build]
bin = "./.air/gofire server run conf/gofire.ini"
cmd = "go build -o ./.air/gofire ./gofire.go"
delay = 1000
exclude_dir = [".air", "data", "dist"]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
full_bin = ""
send_interrupt = true
kill_delay = 2000